#!/usr/bin/env python3
# vi:sw=2:ts=2:expandtab

# Copyright (C) 2009-2025 Ian Munsie
#
# Kosh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kosh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kosh.  If not, see <http://www.gnu.org/licenses/>.

import sys

def disable_ptrace():
  # This prevents the opportunistic attack whereby someone notices kosh left
  # running on an unattended workstation and runs gcore to extract passwords
  # from memory while the owner is distracted. Consider settings such as
  # university computer labs where this sort of attack may take place.
  #
  # This will also boot out an already attached debugger, but this is *NOT*
  # trying to mitigate any attacks involving that avenue, since an existing
  # debugger could easily skip over the prctl call and there's nothing we can
  # really do to stop it. However, such an attack requires advance preparation
  # - it is not opportunistic, and if your threat model includes such an
  # adversary than your only defence is to ensure that they never gain access
  # your workstation to prepare this or any other attack in the first place.
  #
  # Likewise, this does not prevent the root user from reading passwords out of
  # memory - if your adversary has root, you are already owned.
  import ctypes, ctypes.util
  libc = ctypes.CDLL(ctypes.util.find_library('c'))
  PR_SET_DUMPABLE = 4
  try:
    libc.prctl(PR_SET_DUMPABLE, 0, 0, 0, 0)
  except AttributeError: # Not Linux
    pass
if sys.platform != 'win32': # TODO: Implement Windows equivalent
  disable_ptrace()

passdb_default = '~/.kosh/koshdb'

urwid_req_version = '0.9.9.1' # Fixme: what version is actually required?

import version
import os
__version__ = version.__version__
version.checkCrypto()
version.checkUrwid(urwid_req_version)
version.checkPyotp()
if sys.platform in ('win32', 'cygwin'):
  pass
elif version.is_wsl():
  version.checkWSLClipboard()
elif sys.platform == 'darwin':
  pass
elif 'TERMUX_VERSION' in os.environ:
  version.checkTermuxAPI()
else:
  version.checkXClipboard()
version.check_qrcode_import() # Should be done after clipboard check, especially for WSL clipboard
version.check_qrcode_export()

from util.decorators import *
import koshcurses.err
import koshcurses.dialog
import koshcurses.ui

def getParameters():
  import argparse
  parser = argparse.ArgumentParser(
    prog='kosh',
    description='Kosh password manager',
  )
  parser.add_argument('passdb', nargs='?', default=passdb_default,
                      metavar='PASSDB',
                      help='Path to password database (default: %(default)s)')
  parser.add_argument('--keyfile', '-k', action='append', default=[],
                      metavar='FILE', dest='keyfiles',
                      help='Additional key file to load (may be repeated)')
  parser.add_argument('--version', '-V', action='version',
                      version='%%(prog)s %s' % __version__)
  return parser.parse_args()

@handleErr(koshcurses.err.showErr)
def main():
  import koshdb,os
  options = getParameters()
  def prompt(message):
    dialog = koshcurses.dialog.inputDialog(message=message)
    return dialog.showModal()
  key_file_dialog = koshcurses.dialog.KeyFileDialog()
  def key_file_prompt(error=None):
    return key_file_dialog.showModal(error=error)
  try:
    db = koshdb.KoshDB(os.path.expanduser(options.passdb), prompt,
                       key_files=options.keyfiles,
                       key_file_prompt=key_file_prompt)
    u = koshcurses.ui.koshUI(db)
    u.showModal()
  except koshdb.koshdb.FileLocked:
    print('Password database locked by another instance of kosh')
    return
  finally:
    # Clear screen on exit to ensure any displayed passwords are removed from
    # the terminal. On most platforms this will be done automatically when
    # exiting urwid, but some platforms like WSL Windows Terminal doesn't do
    # this automatically so we explicitly do it here.
    if version.is_wsl():
      import ui.ui_tty
      ui.ui_tty.clear()

if __name__ == '__main__':
  main()
